# coding: utf-8
# Macro created by MSC Apex 2024.2 GA - Version CLR:014231-5fbf2aff
# Macro created on Jun 11, 2025 at 22:07:49
# 
# Macro Name = 4_cortes
# 
# Macro Description = 
# 
# Macro Hot Key = 
# 
# Initialize environment for macro execution
# 

import apex
from apex.construct import Point3D, Point2D

apex.setScriptUnitSystem(unitSystemName = r'''mm-kg-s-N-K''')
applicationSettingsGeometry = apex.setting.ApplicationSettingsGeometry()
applicationSettingsGeometry.createGeometryInNewPart = apex.setting.CreateGeometryInNewPart.CurrentPart
applicationSettingsGeometry.geometryTessellationIsWatertight = True
applicationSettingsGeometry.geometryEdgeTesselationTolerance = apex.setting.GeometryTessellationTolerance.Fine
applicationSettingsGeometry.geometryFaceTesselationTolerance = apex.setting.GeometryTessellationTolerance.Fine
apex.setting.setApplicationSettingsGeometry(applicationSettingsGeometry = applicationSettingsGeometry)
applicationSettingsStudy = apex.setting.ApplicationSettingsStudy(useNewScenario = False,displayPrereleaseScenario = False)
apex.setting.setApplicationSettingsStudy(applicationSettingsStudy = applicationSettingsStudy)
model_1 = apex.currentModel()

# 
# Start of recorded operations
# 

# _target = apex.EntityCollection()
# part_1 = apex.getPart( pathName = apex.currentModel().name + "/Union_Apex/Tornillo_Sin_Rosca.1" )
# solid_1 = part_1.getSolid( name = "PartBody" )
# _target.append( solid_1 )
# part_2 = apex.getPart( pathName = apex.currentModel().name + "/Union_Apex/Rosca_Exterior_Tornillo.2" )
# solid_2 = part_2.getSolid( name = "PartBody" )
# _target.append( solid_2 )
# curve_1 = part_2.getCurve( name = "EjeReferencia" )
# _target.append( curve_1 )
# curve_2 = part_2.getCurve( name = "Rosca" )
# _target.append( curve_2 )
# curve_3 = part_2.getCurve( name = "Rosca (2)" )
# _target.append( curve_3 )
# curve_4 = part_2.getCurve( name = "Rosca (3)" )
# _target.append( curve_4 )
# curve_5 = part_2.getCurve( name = "Rosca (4)" )
# _target.append( curve_5 )
# part_3 = apex.getPart( pathName = apex.currentModel().name + "/Union_Apex/Helicoil.1" )
# solid_3 = part_3.getSolid( name = "PartBody" )
# _target.append( solid_3 )
# curve_6 = part_3.getCurve( name = "Helicoil" )
# _target.append( curve_6 )
# curve_7 = part_3.getCurve( name = "Helicoil (2)" )
# _target.append( curve_7 )
# curve_8 = part_3.getCurve( name = "Helicoil (3)" )
# _target.append( curve_8 )
# curve_9 = part_3.getCurve( name = "Helicoil (4)" )
# _target.append( curve_9 )
# curve_10 = part_3.getCurve( name = "Helicoil (5)" )
# _target.append( curve_10 )
# curve_11 = part_3.getCurve( name = "Helicoil (6)" )
# _target.append( curve_11 )
# curve_12 = part_3.getCurve( name = "Helicoil (7)" )
# _target.append( curve_12 )
# curve_13 = part_3.getCurve( name = "Helicoil (8)" )
# _target.append( curve_13 )
# curve_14 = part_3.getCurve( name = "Helicoil (9)" )
# _target.append( curve_14 )
# curve_15 = part_3.getCurve( name = "Helicoil (10)" )
# _target.append( curve_15 )
# curve_16 = part_3.getCurve( name = "Helicoil (11)" )
# _target.append( curve_16 )
# part_4 = apex.getPart( pathName = apex.currentModel().name + "/Union_Apex/Arandela.1" )
# solid_4 = part_4.getSolid( name = "PartBody" )
# _target.append( solid_4 )
# part_5 = apex.getPart( pathName = apex.currentModel().name + "/Union_Apex/PiezaSuperior" )
# solid_5 = part_5.getSolid( name = "PartBody" )
# _target.append( solid_5 )
# part_6 = apex.getPart( pathName = apex.currentModel().name + "/Union_Apex/Product1.1/RoscaPiezaInferior" )
# solid_6 = part_6.getSolid( name = "PartBody" )
# _target.append( solid_6 )
# curve_17 = part_6.getCurve( name = "RoscaExterior" )
# _target.append( curve_17 )
# curve_18 = part_6.getCurve( name = "RoscaExterior (2)" )
# _target.append( curve_18 )
# curve_19 = part_6.getCurve( name = "RoscaExterior (3)" )
# _target.append( curve_19 )
# curve_20 = part_6.getCurve( name = "RoscaExterior (4)" )
# _target.append( curve_20 )
# part_7 = apex.getPart( pathName = apex.currentModel().name + "/Union_Apex/Product1.1/RestoPiezaInferior" )
# solid_7 = part_7.getSolid( name = "Original_PSuperior" )
# _target.append( solid_7 )
# solid_8 = part_7.getSolid( name = "P_InterMed" )
# _target.append( solid_8 )
# solid_9 = part_7.getSolid( name = "P_Inferior_Exterior" )
# _target.append( solid_9 )
# curve_21 = part_7.getCurve( name = "Curve.3" )
# _target.append( curve_21 )
# _location = apex.Coordinate( 7.999998914925279, -4.1694064052133495e-03, -7.999999999740801e-01 )
# part_5 = apex.getPart( pathName = apex.currentModel().name + "/Union_Apex/PiezaSuperior" )
# solid_5 = part_5.getSolid( name = "PartBody" )
# _snapEntity = solid_5.getEdge( id = 3899167 )
# result = apex.geometry.splitOnFeaturePlane(
#     target = _target,
#     location = _location,
#     snapEntity = _snapEntity,
#     splitBehavior = apex.geometry.GeometrySplitBehavior.Partition
# )

# _target = apex.EntityCollection()
# part_1 = apex.getPart( pathName = apex.currentModel().name + "/Union_Apex/Tornillo_Sin_Rosca.1" )
# solid_1 = part_1.getSolid( name = "PartBody" )
# _target.append( solid_1 )
# part_2 = apex.getPart( pathName = apex.currentModel().name + "/Union_Apex/Rosca_Exterior_Tornillo.2" )
# solid_2 = part_2.getSolid( name = "PartBody" )
# _target.append( solid_2 )
# curve_1 = part_2.getCurve( name = "EjeReferencia" )
# _target.append( curve_1 )
# curve_2 = part_2.getCurve( name = "Rosca" )
# _target.append( curve_2 )
# curve_3 = part_2.getCurve( name = "Rosca (2)" )
# _target.append( curve_3 )
# curve_4 = part_2.getCurve( name = "Rosca (3)" )
# _target.append( curve_4 )
# curve_5 = part_2.getCurve( name = "Rosca (4)" )
# _target.append( curve_5 )
# part_3 = apex.getPart( pathName = apex.currentModel().name + "/Union_Apex/Helicoil.1" )
# solid_3 = part_3.getSolid( name = "PartBody" )
# _target.append( solid_3 )
# curve_6 = part_3.getCurve( name = "Helicoil" )
# _target.append( curve_6 )
# curve_7 = part_3.getCurve( name = "Helicoil (2)" )
# _target.append( curve_7 )
# curve_8 = part_3.getCurve( name = "Helicoil (3)" )
# _target.append( curve_8 )
# curve_9 = part_3.getCurve( name = "Helicoil (4)" )
# _target.append( curve_9 )
# curve_10 = part_3.getCurve( name = "Helicoil (5)" )
# _target.append( curve_10 )
# curve_11 = part_3.getCurve( name = "Helicoil (6)" )
# _target.append( curve_11 )
# curve_12 = part_3.getCurve( name = "Helicoil (7)" )
# _target.append( curve_12 )
# curve_13 = part_3.getCurve( name = "Helicoil (8)" )
# _target.append( curve_13 )
# curve_14 = part_3.getCurve( name = "Helicoil (9)" )
# _target.append( curve_14 )
# curve_15 = part_3.getCurve( name = "Helicoil (10)" )
# _target.append( curve_15 )
# curve_16 = part_3.getCurve( name = "Helicoil (11)" )
# _target.append( curve_16 )
# part_4 = apex.getPart( pathName = apex.currentModel().name + "/Union_Apex/Arandela.1" )
# solid_4 = part_4.getSolid( name = "PartBody" )
# _target.append( solid_4 )
# part_5 = apex.getPart( pathName = apex.currentModel().name + "/Union_Apex/PiezaSuperior" )
# solid_5 = part_5.getSolid( name = "PartBody" )
# _target.append( solid_5 )
# part_6 = apex.getPart( pathName = apex.currentModel().name + "/Union_Apex/Product1.1/RoscaPiezaInferior" )
# solid_6 = part_6.getSolid( name = "PartBody" )
# _target.append( solid_6 )
# curve_17 = part_6.getCurve( name = "RoscaExterior" )
# _target.append( curve_17 )
# curve_18 = part_6.getCurve( name = "RoscaExterior (2)" )
# _target.append( curve_18 )
# curve_19 = part_6.getCurve( name = "RoscaExterior (3)" )
# _target.append( curve_19 )
# curve_20 = part_6.getCurve( name = "RoscaExterior (4)" )
# _target.append( curve_20 )
# part_7 = apex.getPart( pathName = apex.currentModel().name + "/Union_Apex/Product1.1/RestoPiezaInferior" )
# solid_7 = part_7.getSolid( name = "Original_PSuperior" )
# _target.append( solid_7 )
# solid_8 = part_7.getSolid( name = "P_InterMed" )
# _target.append( solid_8 )
# solid_9 = part_7.getSolid( name = "P_Inferior_Exterior" )
# _target.append( solid_9 )
# curve_21 = part_7.getCurve( name = "Curve.3" )
# _target.append( curve_21 )
# _location = apex.Coordinate( 2.1423228665912175e-03, 8.000632596374949, -7.999999999740801e-01 )
# part_5 = apex.getPart( pathName = apex.currentModel().name + "/Union_Apex/PiezaSuperior" )
# solid_5 = part_5.getSolid( name = "PartBody" )
# _snapEntity = solid_5.getEdge( id = 3899168 )
# result = apex.geometry.splitOnFeaturePlane(
#     target = _target,
#     location = _location,
#     snapEntity = _snapEntity,
#     splitBehavior = apex.geometry.GeometrySplitBehavior.Partition
# )

# _target = apex.EntityCollection()
# part_1 = apex.getPart( pathName = apex.currentModel().name + "/Union_Apex/Tornillo_Sin_Rosca.1" )
# solid_1 = part_1.getSolid( name = "PartBody" )
# _target.append( solid_1 )
# part_2 = apex.getPart( pathName = apex.currentModel().name + "/Union_Apex/Rosca_Exterior_Tornillo.2" )
# solid_2 = part_2.getSolid( name = "PartBody" )
# _target.append( solid_2 )
# curve_1 = part_2.getCurve( name = "EjeReferencia" )
# _target.append( curve_1 )
# curve_2 = part_2.getCurve( name = "Rosca" )
# _target.append( curve_2 )
# curve_3 = part_2.getCurve( name = "Rosca (2)" )
# _target.append( curve_3 )
# curve_4 = part_2.getCurve( name = "Rosca (3)" )
# _target.append( curve_4 )
# curve_5 = part_2.getCurve( name = "Rosca (4)" )
# _target.append( curve_5 )
# part_3 = apex.getPart( pathName = apex.currentModel().name + "/Union_Apex/Helicoil.1" )
# solid_3 = part_3.getSolid( name = "PartBody" )
# _target.append( solid_3 )
# curve_6 = part_3.getCurve( name = "Helicoil" )
# _target.append( curve_6 )
# curve_7 = part_3.getCurve( name = "Helicoil (2)" )
# _target.append( curve_7 )
# curve_8 = part_3.getCurve( name = "Helicoil (3)" )
# _target.append( curve_8 )
# curve_9 = part_3.getCurve( name = "Helicoil (4)" )
# _target.append( curve_9 )
# curve_10 = part_3.getCurve( name = "Helicoil (5)" )
# _target.append( curve_10 )
# curve_11 = part_3.getCurve( name = "Helicoil (6)" )
# _target.append( curve_11 )
# curve_12 = part_3.getCurve( name = "Helicoil (7)" )
# _target.append( curve_12 )
# curve_13 = part_3.getCurve( name = "Helicoil (8)" )
# _target.append( curve_13 )
# curve_14 = part_3.getCurve( name = "Helicoil (9)" )
# _target.append( curve_14 )
# curve_15 = part_3.getCurve( name = "Helicoil (10)" )
# _target.append( curve_15 )
# curve_16 = part_3.getCurve( name = "Helicoil (11)" )
# _target.append( curve_16 )
# part_4 = apex.getPart( pathName = apex.currentModel().name + "/Union_Apex/Arandela.1" )
# solid_4 = part_4.getSolid( name = "PartBody" )
# _target.append( solid_4 )
# part_5 = apex.getPart( pathName = apex.currentModel().name + "/Union_Apex/PiezaSuperior" )
# solid_5 = part_5.getSolid( name = "PartBody" )
# _target.append( solid_5 )
# part_6 = apex.getPart( pathName = apex.currentModel().name + "/Union_Apex/Product1.1/RoscaPiezaInferior" )
# solid_6 = part_6.getSolid( name = "PartBody" )
# _target.append( solid_6 )
# curve_17 = part_6.getCurve( name = "RoscaExterior" )
# _target.append( curve_17 )
# curve_18 = part_6.getCurve( name = "RoscaExterior (2)" )
# _target.append( curve_18 )
# curve_19 = part_6.getCurve( name = "RoscaExterior (3)" )
# _target.append( curve_19 )
# curve_20 = part_6.getCurve( name = "RoscaExterior (4)" )
# _target.append( curve_20 )
# part_7 = apex.getPart( pathName = apex.currentModel().name + "/Union_Apex/Product1.1/RestoPiezaInferior" )
# solid_7 = part_7.getSolid( name = "Original_PSuperior" )
# _target.append( solid_7 )
# solid_8 = part_7.getSolid( name = "P_InterMed" )
# _target.append( solid_8 )
# solid_9 = part_7.getSolid( name = "P_Inferior_Exterior" )
# _target.append( solid_9 )
# curve_21 = part_7.getCurve( name = "Curve.3" )
# _target.append( curve_21 )
# _location = apex.Coordinate( 5.657728825570911, 5.656285827113546, -7.999999999740801e-01 )
# part_5 = apex.getPart( pathName = apex.currentModel().name + "/Union_Apex/PiezaSuperior" )
# solid_5 = part_5.getSolid( name = "PartBody" )
# _snapEntity = solid_5.getEdge( id = 3899168 )
# result = apex.geometry.splitOnFeaturePlane(
#     target = _target,
#     location = _location,
#     snapEntity = _snapEntity,
#     splitBehavior = apex.geometry.GeometrySplitBehavior.Partition
# )

# _target = apex.EntityCollection()
# part_1 = apex.getPart( pathName = apex.currentModel().name + "/Union_Apex/Tornillo_Sin_Rosca.1" )
# solid_1 = part_1.getSolid( name = "PartBody" )
# _target.append( solid_1 )
# part_2 = apex.getPart( pathName = apex.currentModel().name + "/Union_Apex/Rosca_Exterior_Tornillo.2" )
# solid_2 = part_2.getSolid( name = "PartBody" )
# _target.append( solid_2 )
# curve_1 = part_2.getCurve( name = "EjeReferencia" )
# _target.append( curve_1 )
# curve_2 = part_2.getCurve( name = "Rosca" )
# _target.append( curve_2 )
# curve_3 = part_2.getCurve( name = "Rosca (2)" )
# _target.append( curve_3 )
# curve_4 = part_2.getCurve( name = "Rosca (3)" )
# _target.append( curve_4 )
# curve_5 = part_2.getCurve( name = "Rosca (4)" )
# _target.append( curve_5 )
# part_3 = apex.getPart( pathName = apex.currentModel().name + "/Union_Apex/Helicoil.1" )
# solid_3 = part_3.getSolid( name = "PartBody" )
# _target.append( solid_3 )
# curve_6 = part_3.getCurve( name = "Helicoil" )
# _target.append( curve_6 )
# curve_7 = part_3.getCurve( name = "Helicoil (2)" )
# _target.append( curve_7 )
# curve_8 = part_3.getCurve( name = "Helicoil (3)" )
# _target.append( curve_8 )
# curve_9 = part_3.getCurve( name = "Helicoil (4)" )
# _target.append( curve_9 )
# curve_10 = part_3.getCurve( name = "Helicoil (5)" )
# _target.append( curve_10 )
# curve_11 = part_3.getCurve( name = "Helicoil (6)" )
# _target.append( curve_11 )
# curve_12 = part_3.getCurve( name = "Helicoil (7)" )
# _target.append( curve_12 )
# curve_13 = part_3.getCurve( name = "Helicoil (8)" )
# _target.append( curve_13 )
# curve_14 = part_3.getCurve( name = "Helicoil (9)" )
# _target.append( curve_14 )
# curve_15 = part_3.getCurve( name = "Helicoil (10)" )
# _target.append( curve_15 )
# curve_16 = part_3.getCurve( name = "Helicoil (11)" )
# _target.append( curve_16 )
# part_4 = apex.getPart( pathName = apex.currentModel().name + "/Union_Apex/Arandela.1" )
# solid_4 = part_4.getSolid( name = "PartBody" )
# _target.append( solid_4 )
# part_5 = apex.getPart( pathName = apex.currentModel().name + "/Union_Apex/PiezaSuperior" )
# solid_5 = part_5.getSolid( name = "PartBody" )
# _target.append( solid_5 )
# part_6 = apex.getPart( pathName = apex.currentModel().name + "/Union_Apex/Product1.1/RoscaPiezaInferior" )
# solid_6 = part_6.getSolid( name = "PartBody" )
# _target.append( solid_6 )
# curve_17 = part_6.getCurve( name = "RoscaExterior" )
# _target.append( curve_17 )
# curve_18 = part_6.getCurve( name = "RoscaExterior (2)" )
# _target.append( curve_18 )
# curve_19 = part_6.getCurve( name = "RoscaExterior (3)" )
# _target.append( curve_19 )
# curve_20 = part_6.getCurve( name = "RoscaExterior (4)" )
# _target.append( curve_20 )
# part_7 = apex.getPart( pathName = apex.currentModel().name + "/Union_Apex/Product1.1/RestoPiezaInferior" )
# solid_7 = part_7.getSolid( name = "Original_PSuperior" )
# _target.append( solid_7 )
# solid_8 = part_7.getSolid( name = "P_InterMed" )
# _target.append( solid_8 )
# solid_9 = part_7.getSolid( name = "P_Inferior_Exterior" )
# _target.append( solid_9 )
# curve_21 = part_7.getCurve( name = "Curve.3" )
# _target.append( curve_21 )
# _location = apex.Coordinate( -5.655108284995876, 5.659745766307534, -7.999999999740801e-01 )
# part_5 = apex.getPart( pathName = apex.currentModel().name + "/Union_Apex/PiezaSuperior" )
# solid_5 = part_5.getSolid( name = "PartBody" )
# _snapEntity = solid_5.getEdge( id = 19238 )
# result = apex.geometry.splitOnFeaturePlane(
#     target = _target,
#     location = _location,
#     snapEntity = _snapEntity,
#     splitBehavior = apex.geometry.GeometrySplitBehavior.Partition
# )

# 
# Macro recording stopped on Jun 11, 2025 at 22:09:05
# 



_target = apex.EntityCollection()
part_1 = apex.getPart( pathName = apex.currentModel().name + "/Union_Apex/Tornillo_Sin_Rosca.1" )
solid_1 = part_1.getSolid( name = "PartBody" )
_target.append( solid_1 )
part_2 = apex.getPart( pathName = apex.currentModel().name + "/Union_Apex/Rosca_Exterior_Tornillo.2" )
solid_2 = part_2.getSolid( name = "PartBody" )
_target.append( solid_2 )

part_3 = apex.getPart( pathName = apex.currentModel().name + "/Union_Apex/Helicoil.1" )
solid_3 = part_3.getSolid( name = "PartBody" )
_target.append( solid_3 )

part_4 = apex.getPart( pathName = apex.currentModel().name + "/Union_Apex/Arandela.1" )
solid_4 = part_4.getSolid( name = "PartBody" )
_target.append( solid_4 )
part_5 = apex.getPart( pathName = apex.currentModel().name + "/Union_Apex/PiezaSuperior" )
solid_5 = part_5.getSolid( name = "PartBody" )
_target.append( solid_5 )
part_6 = apex.getPart( pathName = apex.currentModel().name + "/Union_Apex/Product1.1/RoscaPiezaInferior" )
solid_6 = part_6.getSolid( name = "PartBody" )
_target.append( solid_6 )

part_7 = apex.getPart( pathName = apex.currentModel().name + "/Union_Apex/Product1.1/RestoPiezaInferior" )
solid_7 = part_7.getSolid( name = "Original_PSuperior" )
_target.append( solid_7 )
solid_8 = part_7.getSolid( name = "P_InterMed" )
_target.append( solid_8 )
solid_9 = part_7.getSolid( name = "P_Inferior_Exterior" )
_target.append( solid_9 )

_location = apex.Coordinate( 7.999998914925279, -4.1694064052133495e-03, -7.999999999740801e-01 )
part_5 = apex.getPart( pathName = apex.currentModel().name + "/Union_Apex/PiezaSuperior" )
solid_5 = part_5.getSolid( name = "PartBody" )
_snapEntity = solid_5.getEdge( id = 3899167 )
result = apex.geometry.splitOnFeaturePlane(
    target = _target,
    location = _location,
    snapEntity = _snapEntity,
    splitBehavior = apex.geometry.GeometrySplitBehavior.Partition
)


_target = apex.EntityCollection()
part_1 = apex.getPart( pathName = apex.currentModel().name + "/Union_Apex/Tornillo_Sin_Rosca.1" )
solid_1 = part_1.getSolid( name = "PartBody" )
_target.append( solid_1 )
part_2 = apex.getPart( pathName = apex.currentModel().name + "/Union_Apex/Rosca_Exterior_Tornillo.2" )
solid_2 = part_2.getSolid( name = "PartBody" )
_target.append( solid_2 )

part_3 = apex.getPart( pathName = apex.currentModel().name + "/Union_Apex/Helicoil.1" )
solid_3 = part_3.getSolid( name = "PartBody" )
_target.append( solid_3 )

part_4 = apex.getPart( pathName = apex.currentModel().name + "/Union_Apex/Arandela.1" )
solid_4 = part_4.getSolid( name = "PartBody" )
_target.append( solid_4 )
part_5 = apex.getPart( pathName = apex.currentModel().name + "/Union_Apex/PiezaSuperior" )
solid_5 = part_5.getSolid( name = "PartBody" )
_target.append( solid_5 )
part_6 = apex.getPart( pathName = apex.currentModel().name + "/Union_Apex/Product1.1/RoscaPiezaInferior" )
solid_6 = part_6.getSolid( name = "PartBody" )
_target.append( solid_6 )

part_7 = apex.getPart( pathName = apex.currentModel().name + "/Union_Apex/Product1.1/RestoPiezaInferior" )
solid_7 = part_7.getSolid( name = "Original_PSuperior" )
_target.append( solid_7 )
solid_8 = part_7.getSolid( name = "P_InterMed" )
_target.append( solid_8 )
solid_9 = part_7.getSolid( name = "P_Inferior_Exterior" )
_target.append( solid_9 )

_location = apex.Coordinate( 2.1423228665912175e-03, 8.000632596374949, -7.999999999740801e-01 )
part_5 = apex.getPart( pathName = apex.currentModel().name + "/Union_Apex/PiezaSuperior" )
solid_5 = part_5.getSolid( name = "PartBody" )
_snapEntity = solid_5.getEdge( id = 3899168 )
result = apex.geometry.splitOnFeaturePlane(
    target = _target,
    location = _location,
    snapEntity = _snapEntity,
    splitBehavior = apex.geometry.GeometrySplitBehavior.Partition
)


_target = apex.EntityCollection()
part_1 = apex.getPart( pathName = apex.currentModel().name + "/Union_Apex/Tornillo_Sin_Rosca.1" )
solid_1 = part_1.getSolid( name = "PartBody" )
_target.append( solid_1 )
part_2 = apex.getPart( pathName = apex.currentModel().name + "/Union_Apex/Rosca_Exterior_Tornillo.2" )
solid_2 = part_2.getSolid( name = "PartBody" )
_target.append( solid_2 )

part_3 = apex.getPart( pathName = apex.currentModel().name + "/Union_Apex/Helicoil.1" )
solid_3 = part_3.getSolid( name = "PartBody" )
_target.append( solid_3 )

part_4 = apex.getPart( pathName = apex.currentModel().name + "/Union_Apex/Arandela.1" )
solid_4 = part_4.getSolid( name = "PartBody" )
_target.append( solid_4 )
part_5 = apex.getPart( pathName = apex.currentModel().name + "/Union_Apex/PiezaSuperior" )
solid_5 = part_5.getSolid( name = "PartBody" )
_target.append( solid_5 )
part_6 = apex.getPart( pathName = apex.currentModel().name + "/Union_Apex/Product1.1/RoscaPiezaInferior" )
solid_6 = part_6.getSolid( name = "PartBody" )
_target.append( solid_6 )

part_7 = apex.getPart( pathName = apex.currentModel().name + "/Union_Apex/Product1.1/RestoPiezaInferior" )
solid_7 = part_7.getSolid( name = "Original_PSuperior" )
_target.append( solid_7 )
solid_8 = part_7.getSolid( name = "P_InterMed" )
_target.append( solid_8 )
solid_9 = part_7.getSolid( name = "P_Inferior_Exterior" )
_target.append( solid_9 )

_location = apex.Coordinate( 5.657728825570911, 5.656285827113546, -7.999999999740801e-01 )
part_5 = apex.getPart( pathName = apex.currentModel().name + "/Union_Apex/PiezaSuperior" )
solid_5 = part_5.getSolid( name = "PartBody" )
_snapEntity = solid_5.getEdge( id = 3899168 )
result = apex.geometry.splitOnFeaturePlane(
    target = _target,
    location = _location,
    snapEntity = _snapEntity,
    splitBehavior = apex.geometry.GeometrySplitBehavior.Partition
)


_target = apex.EntityCollection()
part_1 = apex.getPart( pathName = apex.currentModel().name + "/Union_Apex/Tornillo_Sin_Rosca.1" )
solid_1 = part_1.getSolid( name = "PartBody" )
_target.append( solid_1 )
part_2 = apex.getPart( pathName = apex.currentModel().name + "/Union_Apex/Rosca_Exterior_Tornillo.2" )
solid_2 = part_2.getSolid( name = "PartBody" )
_target.append( solid_2 )

part_3 = apex.getPart( pathName = apex.currentModel().name + "/Union_Apex/Helicoil.1" )
solid_3 = part_3.getSolid( name = "PartBody" )
_target.append( solid_3 )

part_4 = apex.getPart( pathName = apex.currentModel().name + "/Union_Apex/Arandela.1" )
solid_4 = part_4.getSolid( name = "PartBody" )
_target.append( solid_4 )
part_5 = apex.getPart( pathName = apex.currentModel().name + "/Union_Apex/PiezaSuperior" )
solid_5 = part_5.getSolid( name = "PartBody" )
_target.append( solid_5 )
part_6 = apex.getPart( pathName = apex.currentModel().name + "/Union_Apex/Product1.1/RoscaPiezaInferior" )
solid_6 = part_6.getSolid( name = "PartBody" )
_target.append( solid_6 )

part_7 = apex.getPart( pathName = apex.currentModel().name + "/Union_Apex/Product1.1/RestoPiezaInferior" )
solid_7 = part_7.getSolid( name = "Original_PSuperior" )
_target.append( solid_7 )
solid_8 = part_7.getSolid( name = "P_InterMed" )
_target.append( solid_8 )
solid_9 = part_7.getSolid( name = "P_Inferior_Exterior" )
_target.append( solid_9 )

_location = apex.Coordinate( -5.655108284995876, 5.659745766307534, -7.999999999740801e-01 )
part_5 = apex.getPart( pathName = apex.currentModel().name + "/Union_Apex/PiezaSuperior" )
solid_5 = part_5.getSolid( name = "PartBody" )
_snapEntity = solid_5.getEdge( id = 19238 )
result = apex.geometry.splitOnFeaturePlane(
    target = _target,
    location = _location,
    snapEntity = _snapEntity,
    splitBehavior = apex.geometry.GeometrySplitBehavior.Partition
)